apiVersion: v1
kind: Service
metadata:
  name: go-kyma-user-api
  namespace: go-user-api
  labels:
    app: go-kyma-user-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: go-kyma-user-api